// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Speech.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// AccuracyTest
    /// </summary>
    public partial class AccuracyTest
    {
        /// <summary>
        /// Initializes a new instance of the AccuracyTest class.
        /// </summary>
        public AccuracyTest()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the AccuracyTest class.
        /// </summary>
        /// <param name="referenceModel">The reference model that can be used
        /// to evaluate the improvements and differences</param>
        /// <param name="testModel">The model that is compared to the reference
        /// model</param>
        /// <param name="dataset">Information about the dataset used in the
        /// test</param>
        /// <param name="displayName">The display name of the object</param>
        /// <param name="locale">The locale of the contained data</param>
        /// <param name="testTranscription">Information about the
        /// transcriptions used in the accuracy test with the test
        /// model</param>
        /// <param name="referenceTranscription">Information about the
        /// transcriptions used in the accuracy test with the reference
        /// model</param>
        /// <param name="links">Related links to this accuracy test
        /// entity</param>
        /// <param name="self">The location of this entity</param>
        /// <param name="wordErrorRate">The word error rate of the tested
        /// model</param>
        /// <param name="lastActionDateTime">The time-stamp when the current
        /// status was entered</param>
        /// <param name="status">The status of the object. Possible values
        /// include: 'NotStarted', 'Running', 'Succeeded', 'Failed'</param>
        /// <param name="createdDateTime">The time-stamp when the object was
        /// created</param>
        /// <param name="project">The project, the dataset is associated
        /// with</param>
        /// <param name="description">The description of the object</param>
        /// <param name="properties">The custom properties of this
        /// entity</param>
        public AccuracyTest(EntityReference referenceModel, EntityReference testModel, EntityReference dataset, string displayName, string locale, EntityReference testTranscription = default(EntityReference), EntityReference referenceTranscription = default(EntityReference), FileLinks links = default(FileLinks), string self = default(string), double? wordErrorRate = default(double?), System.DateTime? lastActionDateTime = default(System.DateTime?), string status = default(string), System.DateTime? createdDateTime = default(System.DateTime?), EntityReference project = default(EntityReference), string description = default(string), IDictionary<string, string> properties = default(IDictionary<string, string>))
        {
            TestTranscription = testTranscription;
            ReferenceTranscription = referenceTranscription;
            Links = links;
            Self = self;
            WordErrorRate = wordErrorRate;
            LastActionDateTime = lastActionDateTime;
            Status = status;
            CreatedDateTime = createdDateTime;
            ReferenceModel = referenceModel;
            TestModel = testModel;
            Dataset = dataset;
            Project = project;
            DisplayName = displayName;
            Description = description;
            Properties = properties;
            Locale = locale;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets information about the transcriptions used in the accuracy test
        /// with the test model
        /// </summary>
        [JsonProperty(PropertyName = "testTranscription")]
        public EntityReference TestTranscription { get; private set; }

        /// <summary>
        /// Gets information about the transcriptions used in the accuracy test
        /// with the reference model
        /// </summary>
        [JsonProperty(PropertyName = "referenceTranscription")]
        public EntityReference ReferenceTranscription { get; private set; }

        /// <summary>
        /// Gets related links to this accuracy test entity
        /// </summary>
        [JsonProperty(PropertyName = "links")]
        public FileLinks Links { get; private set; }

        /// <summary>
        /// Gets the location of this entity
        /// </summary>
        [JsonProperty(PropertyName = "self")]
        public string Self { get; private set; }

        /// <summary>
        /// Gets the word error rate of the tested model
        /// </summary>
        [JsonProperty(PropertyName = "wordErrorRate")]
        public double? WordErrorRate { get; private set; }

        /// <summary>
        /// Gets the time-stamp when the current status was entered
        /// </summary>
        [JsonProperty(PropertyName = "lastActionDateTime")]
        public System.DateTime? LastActionDateTime { get; private set; }

        /// <summary>
        /// Gets the status of the object. Possible values include:
        /// 'NotStarted', 'Running', 'Succeeded', 'Failed'
        /// </summary>
        [JsonProperty(PropertyName = "status")]
        public string Status { get; private set; }

        /// <summary>
        /// Gets the time-stamp when the object was created
        /// </summary>
        [JsonProperty(PropertyName = "createdDateTime")]
        public System.DateTime? CreatedDateTime { get; private set; }

        /// <summary>
        /// Gets or sets the reference model that can be used to evaluate the
        /// improvements and differences
        /// </summary>
        [JsonProperty(PropertyName = "referenceModel")]
        public EntityReference ReferenceModel { get; set; }

        /// <summary>
        /// Gets or sets the model that is compared to the reference model
        /// </summary>
        [JsonProperty(PropertyName = "testModel")]
        public EntityReference TestModel { get; set; }

        /// <summary>
        /// Gets or sets information about the dataset used in the test
        /// </summary>
        [JsonProperty(PropertyName = "dataset")]
        public EntityReference Dataset { get; set; }

        /// <summary>
        /// Gets or sets the project, the dataset is associated with
        /// </summary>
        [JsonProperty(PropertyName = "project")]
        public EntityReference Project { get; set; }

        /// <summary>
        /// Gets or sets the display name of the object
        /// </summary>
        [JsonProperty(PropertyName = "displayName")]
        public string DisplayName { get; set; }

        /// <summary>
        /// Gets or sets the description of the object
        /// </summary>
        [JsonProperty(PropertyName = "description")]
        public string Description { get; set; }

        /// <summary>
        /// Gets or sets the custom properties of this entity
        /// </summary>
        [JsonProperty(PropertyName = "properties")]
        public IDictionary<string, string> Properties { get; set; }

        /// <summary>
        /// Gets or sets the locale of the contained data
        /// </summary>
        [JsonProperty(PropertyName = "locale")]
        public string Locale { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (ReferenceModel == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "ReferenceModel");
            }
            if (TestModel == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "TestModel");
            }
            if (Dataset == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Dataset");
            }
            if (DisplayName == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "DisplayName");
            }
            if (Locale == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Locale");
            }
            if (TestTranscription != null)
            {
                TestTranscription.Validate();
            }
            if (ReferenceTranscription != null)
            {
                ReferenceTranscription.Validate();
            }
            if (ReferenceModel != null)
            {
                ReferenceModel.Validate();
            }
            if (TestModel != null)
            {
                TestModel.Validate();
            }
            if (Dataset != null)
            {
                Dataset.Validate();
            }
            if (Project != null)
            {
                Project.Validate();
            }
        }
    }
}
