// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Speech.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// AnalyticsSearchResult
    /// </summary>
    public partial class AnalyticsSearchResult
    {
        /// <summary>
        /// Initializes a new instance of the AnalyticsSearchResult class.
        /// </summary>
        public AnalyticsSearchResult()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the AnalyticsSearchResult class.
        /// </summary>
        /// <param name="itemCount">Item count</param>
        /// <param name="items">Items</param>
        public AnalyticsSearchResult(long? itemCount = default(long?), IList<AnalyticsSearchItem> items = default(IList<AnalyticsSearchItem>))
        {
            ItemCount = itemCount;
            Items = items;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets item count
        /// </summary>
        [JsonProperty(PropertyName = "itemCount")]
        public long? ItemCount { get; set; }

        /// <summary>
        /// Gets or sets items
        /// </summary>
        [JsonProperty(PropertyName = "items")]
        public IList<AnalyticsSearchItem> Items { get; set; }

    }
}
