// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Speech.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// AnalyticsSearchItem
    /// </summary>
    public partial class AnalyticsSearchItem
    {
        /// <summary>
        /// Initializes a new instance of the AnalyticsSearchItem class.
        /// </summary>
        public AnalyticsSearchItem()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the AnalyticsSearchItem class.
        /// </summary>
        /// <param name="fileName">File name</param>
        /// <param name="text">RecognizedPhrases</param>
        /// <param name="created">TimeStamp</param>
        /// <param name="duration">Duration</param>
        /// <param name="transcriptionFile">Transcription file</param>
        /// <param name="audioFile">Audio file</param>
        public AnalyticsSearchItem(string fileName = default(string), string text = default(string), System.DateTime? created = default(System.DateTime?), long? duration = default(long?), string transcriptionFile = default(string), string audioFile = default(string))
        {
            FileName = fileName;
            Text = text;
            Created = created;
            Duration = duration;
            TranscriptionFile = transcriptionFile;
            AudioFile = audioFile;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets file name
        /// </summary>
        [JsonProperty(PropertyName = "fileName")]
        public string FileName { get; set; }

        /// <summary>
        /// Gets or sets recognizedPhrases
        /// </summary>
        [JsonProperty(PropertyName = "text")]
        public string Text { get; set; }

        /// <summary>
        /// Gets or sets timeStamp
        /// </summary>
        [JsonProperty(PropertyName = "created")]
        public System.DateTime? Created { get; set; }

        /// <summary>
        /// Gets or sets duration
        /// </summary>
        [JsonProperty(PropertyName = "duration")]
        public long? Duration { get; set; }

        /// <summary>
        /// Gets or sets transcription file
        /// </summary>
        [JsonProperty(PropertyName = "transcriptionFile")]
        public string TranscriptionFile { get; set; }

        /// <summary>
        /// Gets or sets audio file
        /// </summary>
        [JsonProperty(PropertyName = "audioFile")]
        public string AudioFile { get; set; }

    }
}
