// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Speech.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// CreateSsmlFolderDefinition
    /// </summary>
    public partial class CreateSsmlFolderDefinition
    {
        /// <summary>
        /// Initializes a new instance of the CreateSsmlFolderDefinition class.
        /// </summary>
        public CreateSsmlFolderDefinition()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the CreateSsmlFolderDefinition class.
        /// </summary>
        public CreateSsmlFolderDefinition(System.Guid? parentFolderId = default(System.Guid?), string name = default(string), IList<string> tags = default(IList<string>))
        {
            ParentFolderId = parentFolderId;
            Name = name;
            Tags = tags;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "parentFolderId")]
        public System.Guid? ParentFolderId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "tags")]
        public IList<string> Tags { get; set; }

    }
}
