// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Speech.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// DataCollectionDonationUpdate
    /// </summary>
    public partial class DataCollectionDonationUpdate
    {
        /// <summary>
        /// Initializes a new instance of the DataCollectionDonationUpdate
        /// class.
        /// </summary>
        public DataCollectionDonationUpdate()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the DataCollectionDonationUpdate
        /// class.
        /// </summary>
        /// <param name="displayName">The name of the object</param>
        /// <param name="description">The description of the object</param>
        public DataCollectionDonationUpdate(string displayName = default(string), string description = default(string))
        {
            DisplayName = displayName;
            Description = description;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets the name of the object
        /// </summary>
        [JsonProperty(PropertyName = "displayName")]
        public string DisplayName { get; set; }

        /// <summary>
        /// Gets or sets the description of the object
        /// </summary>
        [JsonProperty(PropertyName = "description")]
        public string Description { get; set; }

    }
}
