// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Speech.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// EditVcgFolderDefinitionV3
    /// </summary>
    public partial class EditVcgFolderDefinitionV3
    {
        /// <summary>
        /// Initializes a new instance of the EditVcgFolderDefinitionV3 class.
        /// </summary>
        public EditVcgFolderDefinitionV3()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the EditVcgFolderDefinitionV3 class.
        /// </summary>
        public EditVcgFolderDefinitionV3(System.Guid? folderTaskId = default(System.Guid?), string name = default(string), bool? isSetTags = default(bool?), IList<string> tags = default(IList<string>))
        {
            FolderTaskId = folderTaskId;
            Name = name;
            IsSetTags = isSetTags;
            Tags = tags;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "folderTaskId")]
        public System.Guid? FolderTaskId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "isSetTags")]
        public bool? IsSetTags { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "tags")]
        public IList<string> Tags { get; set; }

    }
}
