// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Speech.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// EndpointDataDefinition
    /// </summary>
    public partial class EndpointDataDefinition
    {
        /// <summary>
        /// Initializes a new instance of the EndpointDataDefinition class.
        /// </summary>
        public EndpointDataDefinition()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the EndpointDataDefinition class.
        /// </summary>
        /// <param name="startDate">The start date of the demplyment data
        /// export</param>
        /// <param name="endDate">The end date of the demplyment data
        /// export</param>
        /// <param name="name">The name of the object</param>
        /// <param name="locale">The locale of the contained data</param>
        /// <param name="project">The project, the model is associated
        /// with</param>
        /// <param name="description">The description of the object</param>
        /// <param name="properties">The custom properties of this
        /// entity</param>
        public EndpointDataDefinition(System.DateTime startDate, System.DateTime endDate, string name, string locale, ProjectIdentity project = default(ProjectIdentity), System.Guid? endpointId = default(System.Guid?), string description = default(string), IDictionary<string, string> properties = default(IDictionary<string, string>))
        {
            Project = project;
            EndpointId = endpointId;
            StartDate = startDate;
            EndDate = endDate;
            Name = name;
            Description = description;
            Properties = properties;
            Locale = locale;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets the project, the model is associated with
        /// </summary>
        [JsonProperty(PropertyName = "project")]
        public ProjectIdentity Project { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "endpointId")]
        public System.Guid? EndpointId { get; set; }

        /// <summary>
        /// Gets or sets the start date of the demplyment data export
        /// </summary>
        [JsonProperty(PropertyName = "startDate")]
        public System.DateTime StartDate { get; set; }

        /// <summary>
        /// Gets or sets the end date of the demplyment data export
        /// </summary>
        [JsonProperty(PropertyName = "endDate")]
        public System.DateTime EndDate { get; set; }

        /// <summary>
        /// Gets or sets the name of the object
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// Gets or sets the description of the object
        /// </summary>
        [JsonProperty(PropertyName = "description")]
        public string Description { get; set; }

        /// <summary>
        /// Gets or sets the custom properties of this entity
        /// </summary>
        [JsonProperty(PropertyName = "properties")]
        public IDictionary<string, string> Properties { get; set; }

        /// <summary>
        /// Gets or sets the locale of the contained data
        /// </summary>
        [JsonProperty(PropertyName = "locale")]
        public string Locale { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (Name == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Name");
            }
            if (Locale == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Locale");
            }
            if (Project != null)
            {
                Project.Validate();
            }
        }
    }
}
