// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Speech.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// EntityReference
    /// </summary>
    public partial class EntityReference
    {
        /// <summary>
        /// Initializes a new instance of the EntityReference class.
        /// </summary>
        public EntityReference()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the EntityReference class.
        /// </summary>
        /// <param name="self">The location of the referenced entity</param>
        public EntityReference(string self)
        {
            Self = self;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets the location of the referenced entity
        /// </summary>
        [JsonProperty(PropertyName = "self")]
        public string Self { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (Self == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Self");
            }
        }
    }
}
