// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Speech.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// ExportAudioFilesDefinition
    /// </summary>
    public partial class ExportAudioFilesDefinition
    {
        /// <summary>
        /// Initializes a new instance of the ExportAudioFilesDefinition class.
        /// </summary>
        public ExportAudioFilesDefinition()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ExportAudioFilesDefinition class.
        /// </summary>
        public ExportAudioFilesDefinition(string taskName = default(string), string ttsAudioFormat = default(string), IList<ExportAudioFileDefinition> tasks = default(IList<ExportAudioFileDefinition>))
        {
            TaskName = taskName;
            TtsAudioFormat = ttsAudioFormat;
            Tasks = tasks;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "taskName")]
        public string TaskName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ttsAudioFormat")]
        public string TtsAudioFormat { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "tasks")]
        public IList<ExportAudioFileDefinition> Tasks { get; set; }

    }
}
