// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Speech.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// ExportAudioFileDefinition
    /// </summary>
    public partial class ExportAudioFileDefinition
    {
        /// <summary>
        /// Initializes a new instance of the ExportAudioFileDefinition class.
        /// </summary>
        public ExportAudioFileDefinition()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ExportAudioFileDefinition class.
        /// </summary>
        public ExportAudioFileDefinition(System.Guid? taskId = default(System.Guid?), string ssml = default(string))
        {
            TaskId = taskId;
            Ssml = ssml;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "taskId")]
        public System.Guid? TaskId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ssml")]
        public string Ssml { get; set; }

    }
}
