// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Speech.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// IAnalyticsSummaryItem
    /// </summary>
    public partial class IAnalyticsSummaryItem
    {
        /// <summary>
        /// Initializes a new instance of the IAnalyticsSummaryItem class.
        /// </summary>
        public IAnalyticsSummaryItem()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the IAnalyticsSummaryItem class.
        /// </summary>
        /// <param name="name">Name</param>
        /// <param name="value">Value</param>
        public IAnalyticsSummaryItem(string name = default(string), string value = default(string))
        {
            Name = name;
            Value = value;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets name
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// Gets or sets value
        /// </summary>
        [JsonProperty(PropertyName = "value")]
        public string Value { get; set; }

    }
}
