// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Speech.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// IAnalyticsDurationGroup
    /// </summary>
    public partial class IAnalyticsDurationGroup
    {
        /// <summary>
        /// Initializes a new instance of the IAnalyticsDurationGroup class.
        /// </summary>
        public IAnalyticsDurationGroup()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the IAnalyticsDurationGroup class.
        /// </summary>
        /// <param name="name">Name</param>
        /// <param name="durationFrom">DurationFrom</param>
        /// <param name="durationTo">DurationTo</param>
        public IAnalyticsDurationGroup(string name = default(string), double? durationFrom = default(double?), double? durationTo = default(double?))
        {
            Name = name;
            DurationFrom = durationFrom;
            DurationTo = durationTo;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets name
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// Gets or sets durationFrom
        /// </summary>
        [JsonProperty(PropertyName = "durationFrom")]
        public double? DurationFrom { get; set; }

        /// <summary>
        /// Gets or sets durationTo
        /// </summary>
        [JsonProperty(PropertyName = "durationTo")]
        public double? DurationTo { get; set; }

    }
}
