// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Speech.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// InnerError
    /// </summary>
    public partial class InnerError
    {
        /// <summary>
        /// Initializes a new instance of the InnerError class.
        /// </summary>
        public InnerError()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the InnerError class.
        /// </summary>
        /// <param name="code">Possible values include:
        /// 'InvalidParameterValue', 'InvalidRequestBodyFormat',
        /// 'EmptyRequest', 'MissingInputRecords', 'InvalidDocument',
        /// 'ModelVersionIncorrect', 'InvalidDocumentBatch',
        /// 'UnsupportedLanguageCode', 'DataImportFailed', 'InUseViolation',
        /// 'InvalidLocale', 'InvalidBaseModel', 'InvalidAdaptationMapping',
        /// 'InvalidDataset', 'InvalidKeyword', 'InvalidTest', 'FailedDataset',
        /// 'InvalidModel', 'InvalidTranscription', 'InvalidVoiceSynthesis',
        /// 'InvalidPayload', 'InvalidParameter', 'EndpointWithoutLogging',
        /// 'InvalidPermissions', 'InvalidPrerequisite', 'InvalidProductId',
        /// 'InvalidSubscription', 'InvalidProject', 'InvalidProjectKind',
        /// 'InvalidRecordingsUri', 'ExceededNumberOfRecordingsUris',
        /// 'ModelMismatch', 'ProjectGenderMismatch', 'ModelDeprecated',
        /// 'ModelExists', 'ModelNotDeployable', 'EndpointNotUpdatable',
        /// 'SingleDefaultEndpoint', 'InvalidModelUri', 'SubscriptionNotFound',
        /// 'QuotaViolation', 'UnsupportedDelta', 'UnsupportedFilter',
        /// 'UnsupportedPagination', 'UnsupportedOrderBy', 'NoUtf8WithBom',
        /// 'ModelDeploymentNotCompleteState', 'SkuLimitsExist',
        /// 'DeployingFailedModel', 'UnsupportedTimeRange', 'InvalidLogDate',
        /// 'InvalidLogId', 'InvalidLogStartTime', 'InvalidLogEndTime',
        /// 'InvalidTopForLogs', 'DeleteNotAllowed', 'Forbidden',
        /// 'DeployNotAllowed', 'UnexpectedError', 'InvalidCollection',
        /// 'InvalidCallbackUri'</param>
        /// <param name="details">IDictionary`2</param>
        public InnerError(string code = default(string), IDictionary<string, string> details = default(IDictionary<string, string>), string message = default(string), string target = default(string), InnerError innerErrorProperty = default(InnerError))
        {
            Code = code;
            Details = details;
            Message = message;
            Target = target;
            InnerErrorProperty = innerErrorProperty;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets possible values include: 'InvalidParameterValue',
        /// 'InvalidRequestBodyFormat', 'EmptyRequest', 'MissingInputRecords',
        /// 'InvalidDocument', 'ModelVersionIncorrect', 'InvalidDocumentBatch',
        /// 'UnsupportedLanguageCode', 'DataImportFailed', 'InUseViolation',
        /// 'InvalidLocale', 'InvalidBaseModel', 'InvalidAdaptationMapping',
        /// 'InvalidDataset', 'InvalidKeyword', 'InvalidTest', 'FailedDataset',
        /// 'InvalidModel', 'InvalidTranscription', 'InvalidVoiceSynthesis',
        /// 'InvalidPayload', 'InvalidParameter', 'EndpointWithoutLogging',
        /// 'InvalidPermissions', 'InvalidPrerequisite', 'InvalidProductId',
        /// 'InvalidSubscription', 'InvalidProject', 'InvalidProjectKind',
        /// 'InvalidRecordingsUri', 'ExceededNumberOfRecordingsUris',
        /// 'ModelMismatch', 'ProjectGenderMismatch', 'ModelDeprecated',
        /// 'ModelExists', 'ModelNotDeployable', 'EndpointNotUpdatable',
        /// 'SingleDefaultEndpoint', 'InvalidModelUri', 'SubscriptionNotFound',
        /// 'QuotaViolation', 'UnsupportedDelta', 'UnsupportedFilter',
        /// 'UnsupportedPagination', 'UnsupportedOrderBy', 'NoUtf8WithBom',
        /// 'ModelDeploymentNotCompleteState', 'SkuLimitsExist',
        /// 'DeployingFailedModel', 'UnsupportedTimeRange', 'InvalidLogDate',
        /// 'InvalidLogId', 'InvalidLogStartTime', 'InvalidLogEndTime',
        /// 'InvalidTopForLogs', 'DeleteNotAllowed', 'Forbidden',
        /// 'DeployNotAllowed', 'UnexpectedError', 'InvalidCollection',
        /// 'InvalidCallbackUri'
        /// </summary>
        [JsonProperty(PropertyName = "code")]
        public string Code { get; set; }

        /// <summary>
        /// Gets or sets iDictionary`2
        /// </summary>
        [JsonProperty(PropertyName = "details")]
        public IDictionary<string, string> Details { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "message")]
        public string Message { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "target")]
        public string Target { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "innerError")]
        public InnerError InnerErrorProperty { get; set; }

    }
}
