// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Speech.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// InnerErrorV2
    /// </summary>
    /// <remarks>
    /// An implementation of this interface represents a stage in a stack
    /// trace.
    /// If the error levvel is the root, the
    /// {Microsoft.SpeechServices.Common.Client.IInnerError.Code} and the
    /// {Microsoft.SpeechServices.Common.Client.IInnerError.InnerError}
    /// property may be omitted.
    /// </remarks>
    public partial class InnerErrorV2
    {
        /// <summary>
        /// Initializes a new instance of the InnerErrorV2 class.
        /// </summary>
        public InnerErrorV2()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the InnerErrorV2 class.
        /// </summary>
        /// <param name="code">A service-defined error code that should be
        /// human-readable.
        /// This code serves as a more specific indicator of the error than
        /// the HTTP error code specified in the response</param>
        /// <param name="innererror">A human-readable representation of the
        /// error. It is intended as
        /// an aid to developers and is not suitable for exposure to end
        /// users</param>
        public InnerErrorV2(string code = default(string), InnerErrorV2 innererror = default(InnerErrorV2))
        {
            Code = code;
            Innererror = innererror;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets a service-defined error code that should be
        /// human-readable.
        /// This code serves as a more specific indicator of the error than
        /// the HTTP error code specified in the response
        /// </summary>
        [JsonProperty(PropertyName = "code")]
        public string Code { get; set; }

        /// <summary>
        /// Gets or sets a human-readable representation of the error. It is
        /// intended as
        /// an aid to developers and is not suitable for exposure to end users
        /// </summary>
        [JsonProperty(PropertyName = "innererror")]
        public InnerErrorV2 Innererror { get; set; }

    }
}
