// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Speech.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// KeywordDataset
    /// </summary>
    public partial class KeywordDataset
    {
        /// <summary>
        /// Initializes a new instance of the KeywordDataset class.
        /// </summary>
        public KeywordDataset()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the KeywordDataset class.
        /// </summary>
        /// <param name="dataUrl">The URL of the data for the dataset</param>
        /// <param name="dataImportKind">The kind of the dataset (e.g.,
        /// acoustic data, language data, ...). Possible values include:
        /// 'Acoustic', 'Language', 'Pronunciation', 'AudioFiles', 'None',
        /// 'CustomVoice', 'KeywordAudioTranscript'</param>
        /// <param name="displayName">The display name of the object</param>
        /// <param name="locale">The locale of the contained data</param>
        /// <param name="project">The project, the dataset is associated
        /// with</param>
        /// <param name="links">The location to get all files of this
        /// entity</param>
        /// <param name="self">The location of this entity</param>
        /// <param name="description">The description of the object</param>
        /// <param name="lastActionDateTime">The time-stamp when the current
        /// status was entered</param>
        /// <param name="status">The status of the object. Possible values
        /// include: 'NotStarted', 'Running', 'Succeeded', 'Failed'</param>
        /// <param name="createdDateTime">The time-stamp when the object was
        /// created</param>
        /// <param name="properties">The custom properties of this
        /// entity</param>
        public KeywordDataset(string dataUrl, string dataImportKind, string displayName, string locale, EntityReference project = default(EntityReference), FileLinks links = default(FileLinks), string self = default(string), string description = default(string), System.DateTime? lastActionDateTime = default(System.DateTime?), string status = default(string), System.DateTime? createdDateTime = default(System.DateTime?), IDictionary<string, string> properties = default(IDictionary<string, string>))
        {
            Project = project;
            DataUrl = dataUrl;
            Links = links;
            DataImportKind = dataImportKind;
            Self = self;
            DisplayName = displayName;
            Description = description;
            LastActionDateTime = lastActionDateTime;
            Status = status;
            CreatedDateTime = createdDateTime;
            Properties = properties;
            Locale = locale;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets the project, the dataset is associated with
        /// </summary>
        [JsonProperty(PropertyName = "project")]
        public EntityReference Project { get; set; }

        /// <summary>
        /// Gets or sets the URL of the data for the dataset
        /// </summary>
        [JsonProperty(PropertyName = "dataUrl")]
        public string DataUrl { get; set; }

        /// <summary>
        /// Gets the location to get all files of this entity
        /// </summary>
        [JsonProperty(PropertyName = "links")]
        public FileLinks Links { get; private set; }

        /// <summary>
        /// Gets or sets the kind of the dataset (e.g., acoustic data, language
        /// data, ...). Possible values include: 'Acoustic', 'Language',
        /// 'Pronunciation', 'AudioFiles', 'None', 'CustomVoice',
        /// 'KeywordAudioTranscript'
        /// </summary>
        [JsonProperty(PropertyName = "dataImportKind")]
        public string DataImportKind { get; set; }

        /// <summary>
        /// Gets the location of this entity
        /// </summary>
        [JsonProperty(PropertyName = "self")]
        public string Self { get; private set; }

        /// <summary>
        /// Gets or sets the display name of the object
        /// </summary>
        [JsonProperty(PropertyName = "displayName")]
        public string DisplayName { get; set; }

        /// <summary>
        /// Gets or sets the description of the object
        /// </summary>
        [JsonProperty(PropertyName = "description")]
        public string Description { get; set; }

        /// <summary>
        /// Gets the time-stamp when the current status was entered
        /// </summary>
        [JsonProperty(PropertyName = "lastActionDateTime")]
        public System.DateTime? LastActionDateTime { get; private set; }

        /// <summary>
        /// Gets the status of the object. Possible values include:
        /// 'NotStarted', 'Running', 'Succeeded', 'Failed'
        /// </summary>
        [JsonProperty(PropertyName = "status")]
        public string Status { get; private set; }

        /// <summary>
        /// Gets the time-stamp when the object was created
        /// </summary>
        [JsonProperty(PropertyName = "createdDateTime")]
        public System.DateTime? CreatedDateTime { get; private set; }

        /// <summary>
        /// Gets or sets the custom properties of this entity
        /// </summary>
        [JsonProperty(PropertyName = "properties")]
        public IDictionary<string, string> Properties { get; set; }

        /// <summary>
        /// Gets or sets the locale of the contained data
        /// </summary>
        [JsonProperty(PropertyName = "locale")]
        public string Locale { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (DataUrl == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "DataUrl");
            }
            if (DataImportKind == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "DataImportKind");
            }
            if (DisplayName == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "DisplayName");
            }
            if (Locale == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Locale");
            }
            if (Project != null)
            {
                Project.Validate();
            }
        }
    }
}
