// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Speech.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// ModelProperties
    /// </summary>
    public partial class ModelProperties
    {
        /// <summary>
        /// Initializes a new instance of the ModelProperties class.
        /// </summary>
        public ModelProperties()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ModelProperties class.
        /// </summary>
        /// <param name="deprecatedFeatures">The deprecated features for this
        /// model. Possible values include: 'None', 'Adaptation',
        /// 'Transcription'</param>
        /// <param name="email">The email address to send email notifications
        /// to in case the operation completes.
        /// The value will be removed after successfully sending the
        /// email</param>
        public ModelProperties(string deprecatedFeatures = default(string), string email = default(string))
        {
            DeprecatedFeatures = deprecatedFeatures;
            Email = email;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets the deprecated features for this model. Possible values
        /// include: 'None', 'Adaptation', 'Transcription'
        /// </summary>
        [JsonProperty(PropertyName = "deprecatedFeatures")]
        public string DeprecatedFeatures { get; private set; }

        /// <summary>
        /// Gets or sets the email address to send email notifications to in
        /// case the operation completes.
        /// The value will be removed after successfully sending the email
        /// </summary>
        [JsonProperty(PropertyName = "email")]
        public string Email { get; set; }

    }
}
