// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Speech.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// ModelLinks
    /// </summary>
    public partial class ModelLinks
    {
        /// <summary>
        /// Initializes a new instance of the ModelLinks class.
        /// </summary>
        public ModelLinks()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ModelLinks class.
        /// </summary>
        /// <param name="endpointManifest">The location to get an endpoint
        /// manifest for this model</param>
        /// <param name="copy">The location to the model copy action</param>
        public ModelLinks(string endpointManifest = default(string), string copy = default(string))
        {
            EndpointManifest = endpointManifest;
            Copy = copy;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets the location to get an endpoint manifest for this model
        /// </summary>
        [JsonProperty(PropertyName = "endpointManifest")]
        public string EndpointManifest { get; private set; }

        /// <summary>
        /// Gets the location to the model copy action
        /// </summary>
        [JsonProperty(PropertyName = "copy")]
        public string Copy { get; private set; }

    }
}
