// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Speech.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// Model
    /// </summary>
    public partial class Model
    {
        /// <summary>
        /// Initializes a new instance of the Model class.
        /// </summary>
        public Model()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the Model class.
        /// </summary>
        /// <param name="displayName">The display name of the object</param>
        /// <param name="modelKind">The kind of this model (e.g. acoustic,
        /// language ...). Possible values include: 'Acoustic', 'Language',
        /// 'AcousticAndLanguage'</param>
        /// <param name="locale">The locale of the contained data</param>
        /// <param name="project">The project, the model is associated
        /// with</param>
        /// <param name="links">Related links to this model entity</param>
        /// <param name="modelProperties">Additional configuration options when
        /// creating a new model and additional metadata provided by the
        /// service</param>
        /// <param name="self">The location of this entity</param>
        /// <param name="description">The description of the object</param>
        /// <param name="text">The text used to adapt this language
        /// model</param>
        /// <param name="baseModel">The base model used for adaptation</param>
        /// <param name="datasets">Datasets used for adaptation</param>
        /// <param name="properties">The custom properties of this
        /// entity</param>
        /// <param name="lastActionDateTime">The time-stamp when the current
        /// status was entered</param>
        /// <param name="status">The status of the object. Possible values
        /// include: 'NotStarted', 'Running', 'Succeeded', 'Failed'</param>
        /// <param name="createdDateTime">The time-stamp when the object was
        /// created</param>
        public Model(string displayName, string modelKind, string locale, EntityReference project = default(EntityReference), ModelLinks links = default(ModelLinks), ModelProperties modelProperties = default(ModelProperties), string self = default(string), string description = default(string), string text = default(string), EntityReference baseModel = default(EntityReference), IList<EntityReference> datasets = default(IList<EntityReference>), IDictionary<string, string> properties = default(IDictionary<string, string>), System.DateTime? lastActionDateTime = default(System.DateTime?), string status = default(string), System.DateTime? createdDateTime = default(System.DateTime?))
        {
            Project = project;
            Links = links;
            ModelProperties = modelProperties;
            Self = self;
            DisplayName = displayName;
            Description = description;
            ModelKind = modelKind;
            Text = text;
            BaseModel = baseModel;
            Datasets = datasets;
            Properties = properties;
            Locale = locale;
            LastActionDateTime = lastActionDateTime;
            Status = status;
            CreatedDateTime = createdDateTime;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets the project, the model is associated with
        /// </summary>
        [JsonProperty(PropertyName = "project")]
        public EntityReference Project { get; set; }

        /// <summary>
        /// Gets related links to this model entity
        /// </summary>
        [JsonProperty(PropertyName = "links")]
        public ModelLinks Links { get; private set; }

        /// <summary>
        /// Gets or sets additional configuration options when creating a new
        /// model and additional metadata provided by the service
        /// </summary>
        [JsonProperty(PropertyName = "modelProperties")]
        public ModelProperties ModelProperties { get; set; }

        /// <summary>
        /// Gets the location of this entity
        /// </summary>
        [JsonProperty(PropertyName = "self")]
        public string Self { get; private set; }

        /// <summary>
        /// Gets or sets the display name of the object
        /// </summary>
        [JsonProperty(PropertyName = "displayName")]
        public string DisplayName { get; set; }

        /// <summary>
        /// Gets or sets the description of the object
        /// </summary>
        [JsonProperty(PropertyName = "description")]
        public string Description { get; set; }

        /// <summary>
        /// Gets or sets the kind of this model (e.g. acoustic, language ...).
        /// Possible values include: 'Acoustic', 'Language',
        /// 'AcousticAndLanguage'
        /// </summary>
        [JsonProperty(PropertyName = "modelKind")]
        public string ModelKind { get; set; }

        /// <summary>
        /// Gets or sets the text used to adapt this language model
        /// </summary>
        [JsonProperty(PropertyName = "text")]
        public string Text { get; set; }

        /// <summary>
        /// Gets or sets the base model used for adaptation
        /// </summary>
        [JsonProperty(PropertyName = "baseModel")]
        public EntityReference BaseModel { get; set; }

        /// <summary>
        /// Gets or sets datasets used for adaptation
        /// </summary>
        [JsonProperty(PropertyName = "datasets")]
        public IList<EntityReference> Datasets { get; set; }

        /// <summary>
        /// Gets or sets the custom properties of this entity
        /// </summary>
        [JsonProperty(PropertyName = "properties")]
        public IDictionary<string, string> Properties { get; set; }

        /// <summary>
        /// Gets or sets the locale of the contained data
        /// </summary>
        [JsonProperty(PropertyName = "locale")]
        public string Locale { get; set; }

        /// <summary>
        /// Gets the time-stamp when the current status was entered
        /// </summary>
        [JsonProperty(PropertyName = "lastActionDateTime")]
        public System.DateTime? LastActionDateTime { get; private set; }

        /// <summary>
        /// Gets the status of the object. Possible values include:
        /// 'NotStarted', 'Running', 'Succeeded', 'Failed'
        /// </summary>
        [JsonProperty(PropertyName = "status")]
        public string Status { get; private set; }

        /// <summary>
        /// Gets the time-stamp when the object was created
        /// </summary>
        [JsonProperty(PropertyName = "createdDateTime")]
        public System.DateTime? CreatedDateTime { get; private set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (DisplayName == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "DisplayName");
            }
            if (ModelKind == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "ModelKind");
            }
            if (Locale == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Locale");
            }
            if (Project != null)
            {
                Project.Validate();
            }
            if (BaseModel != null)
            {
                BaseModel.Validate();
            }
            if (Datasets != null)
            {
                foreach (var element in Datasets)
                {
                    if (element != null)
                    {
                        element.Validate();
                    }
                }
            }
        }
    }
}
