// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Speech.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class ModelTrainingLocales
    {
        /// <summary>
        /// Initializes a new instance of the ModelTrainingLocales class.
        /// </summary>
        public ModelTrainingLocales()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ModelTrainingLocales class.
        /// </summary>
        public ModelTrainingLocales(IList<string> none = default(IList<string>), IList<string> acoustic = default(IList<string>), IList<string> language = default(IList<string>), IList<string> acousticAndLanguage = default(IList<string>), IList<string> customVoice = default(IList<string>), IList<string> sentiment = default(IList<string>), IList<string> languageIdentification = default(IList<string>), IList<string> diarization = default(IList<string>), IList<string> keyword = default(IList<string>), IList<string> pronunciationScore = default(IList<string>))
        {
            None = none;
            Acoustic = acoustic;
            Language = language;
            AcousticAndLanguage = acousticAndLanguage;
            CustomVoice = customVoice;
            Sentiment = sentiment;
            LanguageIdentification = languageIdentification;
            Diarization = diarization;
            Keyword = keyword;
            PronunciationScore = pronunciationScore;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "None")]
        public IList<string> None { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Acoustic")]
        public IList<string> Acoustic { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Language")]
        public IList<string> Language { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "AcousticAndLanguage")]
        public IList<string> AcousticAndLanguage { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "CustomVoice")]
        public IList<string> CustomVoice { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Sentiment")]
        public IList<string> Sentiment { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "LanguageIdentification")]
        public IList<string> LanguageIdentification { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Diarization")]
        public IList<string> Diarization { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Keyword")]
        public IList<string> Keyword { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "PronunciationScore")]
        public IList<string> PronunciationScore { get; set; }

    }
}
