// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Speech.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// ProjectProperties
    /// </summary>
    public partial class ProjectProperties
    {
        /// <summary>
        /// Initializes a new instance of the ProjectProperties class.
        /// </summary>
        public ProjectProperties()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ProjectProperties class.
        /// </summary>
        /// <param name="datasetCount">The number of datasets associated to
        /// this project</param>
        /// <param name="accuracyTestCount">The number of accuracy tests
        /// associated to this project</param>
        /// <param name="modelCount">The number of models associated to this
        /// project</param>
        /// <param name="transcriptionCount">The number of transcription
        /// associated to this project</param>
        /// <param name="endpointCount">The number of endpoints associated to
        /// this project</param>
        public ProjectProperties(int? datasetCount = default(int?), int? accuracyTestCount = default(int?), int? modelCount = default(int?), int? transcriptionCount = default(int?), int? endpointCount = default(int?))
        {
            DatasetCount = datasetCount;
            AccuracyTestCount = accuracyTestCount;
            ModelCount = modelCount;
            TranscriptionCount = transcriptionCount;
            EndpointCount = endpointCount;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets the number of datasets associated to this project
        /// </summary>
        [JsonProperty(PropertyName = "datasetCount")]
        public int? DatasetCount { get; private set; }

        /// <summary>
        /// Gets the number of accuracy tests associated to this project
        /// </summary>
        [JsonProperty(PropertyName = "accuracyTestCount")]
        public int? AccuracyTestCount { get; private set; }

        /// <summary>
        /// Gets the number of models associated to this project
        /// </summary>
        [JsonProperty(PropertyName = "modelCount")]
        public int? ModelCount { get; private set; }

        /// <summary>
        /// Gets the number of transcription associated to this project
        /// </summary>
        [JsonProperty(PropertyName = "transcriptionCount")]
        public int? TranscriptionCount { get; private set; }

        /// <summary>
        /// Gets the number of endpoints associated to this project
        /// </summary>
        [JsonProperty(PropertyName = "endpointCount")]
        public int? EndpointCount { get; private set; }

    }
}
