// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Speech.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// ProjectLinks
    /// </summary>
    public partial class ProjectLinks
    {
        /// <summary>
        /// Initializes a new instance of the ProjectLinks class.
        /// </summary>
        public ProjectLinks()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ProjectLinks class.
        /// </summary>
        /// <param name="accuracyTests">The location of the location to get a
        /// list of all accuracy tests of this project</param>
        /// <param name="datasets">The location to get a list of all datasets
        /// of this project</param>
        /// <param name="modelsProperty">The location to get a list of all
        /// models of this project</param>
        /// <param name="endpoints">The location to get a list of all endpoints
        /// of this project</param>
        /// <param name="transcriptions">The location to get a list of all
        /// transcriptions of this project</param>
        public ProjectLinks(string accuracyTests = default(string), string datasets = default(string), string modelsProperty = default(string), string endpoints = default(string), string transcriptions = default(string))
        {
            AccuracyTests = accuracyTests;
            Datasets = datasets;
            ModelsProperty = modelsProperty;
            Endpoints = endpoints;
            Transcriptions = transcriptions;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets the location of the location to get a list of all accuracy
        /// tests of this project
        /// </summary>
        [JsonProperty(PropertyName = "accuracyTests")]
        public string AccuracyTests { get; private set; }

        /// <summary>
        /// Gets the location to get a list of all datasets of this project
        /// </summary>
        [JsonProperty(PropertyName = "datasets")]
        public string Datasets { get; private set; }

        /// <summary>
        /// Gets the location to get a list of all models of this project
        /// </summary>
        [JsonProperty(PropertyName = "models")]
        public string ModelsProperty { get; private set; }

        /// <summary>
        /// Gets the location to get a list of all endpoints of this project
        /// </summary>
        [JsonProperty(PropertyName = "endpoints")]
        public string Endpoints { get; private set; }

        /// <summary>
        /// Gets the location to get a list of all transcriptions of this
        /// project
        /// </summary>
        [JsonProperty(PropertyName = "transcriptions")]
        public string Transcriptions { get; private set; }

    }
}
