// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Speech.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// QueryExportAudioTasksResponse
    /// </summary>
    public partial class QueryExportAudioTasksResponse
    {
        /// <summary>
        /// Initializes a new instance of the QueryExportAudioTasksResponse
        /// class.
        /// </summary>
        public QueryExportAudioTasksResponse()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the QueryExportAudioTasksResponse
        /// class.
        /// </summary>
        public QueryExportAudioTasksResponse(IList<QueryExportAudioTaskResponse> tasks = default(IList<QueryExportAudioTaskResponse>))
        {
            Tasks = tasks;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "tasks")]
        public IList<QueryExportAudioTaskResponse> Tasks { get; set; }

    }
}
