// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Speech.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// QueryConditionItemDefinition
    /// </summary>
    public partial class QueryConditionItemDefinition
    {
        /// <summary>
        /// Initializes a new instance of the QueryConditionItemDefinition
        /// class.
        /// </summary>
        public QueryConditionItemDefinition()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the QueryConditionItemDefinition
        /// class.
        /// </summary>
        /// <param name="operatorKind">Possible values include: 'None',
        /// 'Equal', 'Contains'</param>
        public QueryConditionItemDefinition(string name = default(string), string value = default(string), string operatorKind = default(string))
        {
            Name = name;
            Value = value;
            OperatorKind = operatorKind;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "value")]
        public string Value { get; set; }

        /// <summary>
        /// Gets or sets possible values include: 'None', 'Equal', 'Contains'
        /// </summary>
        [JsonProperty(PropertyName = "operatorKind")]
        public string OperatorKind { get; set; }

    }
}
