// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Speech.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// QueryAudioFileResponse
    /// </summary>
    public partial class QueryAudioFileResponse
    {
        /// <summary>
        /// Initializes a new instance of the QueryAudioFileResponse class.
        /// </summary>
        public QueryAudioFileResponse()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the QueryAudioFileResponse class.
        /// </summary>
        /// <param name="id">The identifier of this entity</param>
        /// <param name="name">The name of the object</param>
        /// <param name="state">Possible values include: 'None', 'Waiting',
        /// 'Processing', 'Complete', 'Failed', 'Deleting'</param>
        /// <param name="createdDateTime">The time-stamp when the object was
        /// created</param>
        /// <param name="description">The description of the object</param>
        /// <param name="properties">The custom properties of this
        /// entity</param>
        public QueryAudioFileResponse(System.Guid id, string name, VcgFile ssmlTaskFile = default(VcgFile), VcgBlobEntityDefinition audio = default(VcgBlobEntityDefinition), VcgBlobEntityDefinition ssmlSnapshot = default(VcgBlobEntityDefinition), string state = default(string), System.DateTime? createdDateTime = default(System.DateTime?), string description = default(string), IDictionary<string, string> properties = default(IDictionary<string, string>))
        {
            SsmlTaskFile = ssmlTaskFile;
            Audio = audio;
            SsmlSnapshot = ssmlSnapshot;
            State = state;
            Id = id;
            CreatedDateTime = createdDateTime;
            Name = name;
            Description = description;
            Properties = properties;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ssmlTaskFile")]
        public VcgFile SsmlTaskFile { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "audio")]
        public VcgBlobEntityDefinition Audio { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ssmlSnapshot")]
        public VcgBlobEntityDefinition SsmlSnapshot { get; set; }

        /// <summary>
        /// Gets or sets possible values include: 'None', 'Waiting',
        /// 'Processing', 'Complete', 'Failed', 'Deleting'
        /// </summary>
        [JsonProperty(PropertyName = "state")]
        public string State { get; set; }

        /// <summary>
        /// Gets or sets the identifier of this entity
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public System.Guid Id { get; set; }

        /// <summary>
        /// Gets the time-stamp when the object was created
        /// </summary>
        [JsonProperty(PropertyName = "createdDateTime")]
        public System.DateTime? CreatedDateTime { get; private set; }

        /// <summary>
        /// Gets or sets the name of the object
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// Gets or sets the description of the object
        /// </summary>
        [JsonProperty(PropertyName = "description")]
        public string Description { get; set; }

        /// <summary>
        /// Gets or sets the custom properties of this entity
        /// </summary>
        [JsonProperty(PropertyName = "properties")]
        public IDictionary<string, string> Properties { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (Name == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Name");
            }
            if (SsmlTaskFile != null)
            {
                SsmlTaskFile.Validate();
            }
            if (Audio != null)
            {
                Audio.Validate();
            }
            if (SsmlSnapshot != null)
            {
                SsmlSnapshot.Validate();
            }
        }
    }
}
