// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Speech.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// QueryConditionDefinition
    /// </summary>
    public partial class QueryConditionDefinition
    {
        /// <summary>
        /// Initializes a new instance of the QueryConditionDefinition class.
        /// </summary>
        public QueryConditionDefinition()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the QueryConditionDefinition class.
        /// </summary>
        /// <param name="responseSettings">IDictionary`2</param>
        public QueryConditionDefinition(IList<QueryConditionItemDefinition> items = default(IList<QueryConditionItemDefinition>), QueryPagingDefinition paging = default(QueryPagingDefinition), QueryOrderByDefinition orderBy = default(QueryOrderByDefinition), IDictionary<string, string> responseSettings = default(IDictionary<string, string>))
        {
            Items = items;
            Paging = paging;
            OrderBy = orderBy;
            ResponseSettings = responseSettings;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "items")]
        public IList<QueryConditionItemDefinition> Items { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "paging")]
        public QueryPagingDefinition Paging { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "orderBy")]
        public QueryOrderByDefinition OrderBy { get; set; }

        /// <summary>
        /// Gets or sets iDictionary`2
        /// </summary>
        [JsonProperty(PropertyName = "responseSettings")]
        public IDictionary<string, string> ResponseSettings { get; set; }

    }
}
