// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Speech.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// QueryOrderByDefinition
    /// </summary>
    public partial class QueryOrderByDefinition
    {
        /// <summary>
        /// Initializes a new instance of the QueryOrderByDefinition class.
        /// </summary>
        public QueryOrderByDefinition()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the QueryOrderByDefinition class.
        /// </summary>
        public QueryOrderByDefinition(string fieldId = default(string), bool? isDesc = default(bool?))
        {
            FieldId = fieldId;
            IsDesc = isDesc;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "fieldId")]
        public string FieldId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "isDesc")]
        public bool? IsDesc { get; set; }

    }
}
