// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Speech.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// QuerySsmlFilesResponseV3
    /// </summary>
    public partial class QuerySsmlFilesResponseV3
    {
        /// <summary>
        /// Initializes a new instance of the QuerySsmlFilesResponseV3 class.
        /// </summary>
        public QuerySsmlFilesResponseV3()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the QuerySsmlFilesResponseV3 class.
        /// </summary>
        public QuerySsmlFilesResponseV3(IList<IVcgTask> ssmlFolderOrFiles = default(IList<IVcgTask>), IList<IVcgTask> tasks = default(IList<IVcgTask>))
        {
            SsmlFolderOrFiles = ssmlFolderOrFiles;
            Tasks = tasks;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ssmlFolderOrFiles")]
        public IList<IVcgTask> SsmlFolderOrFiles { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "tasks")]
        public IList<IVcgTask> Tasks { get; set; }

    }
}
