// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Speech.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// QuerySsmlFilesDefinitionV3
    /// </summary>
    public partial class QuerySsmlFilesDefinitionV3
    {
        /// <summary>
        /// Initializes a new instance of the QuerySsmlFilesDefinitionV3 class.
        /// </summary>
        public QuerySsmlFilesDefinitionV3()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the QuerySsmlFilesDefinitionV3 class.
        /// </summary>
        public QuerySsmlFilesDefinitionV3(bool? isQueryChildren = default(bool?), bool? isQueryParents = default(bool?), bool? isRecursive = default(bool?), bool? isFlatten = default(bool?), QueryConditionDefinition queryCondition = default(QueryConditionDefinition))
        {
            IsQueryChildren = isQueryChildren;
            IsQueryParents = isQueryParents;
            IsRecursive = isRecursive;
            IsFlatten = isFlatten;
            QueryCondition = queryCondition;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "isQueryChildren")]
        public bool? IsQueryChildren { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "isQueryParents")]
        public bool? IsQueryParents { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "isRecursive")]
        public bool? IsRecursive { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "isFlatten")]
        public bool? IsFlatten { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "queryCondition")]
        public QueryConditionDefinition QueryCondition { get; set; }

    }
}
