// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Speech.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// QueryAudioFilesResponse
    /// </summary>
    public partial class QueryAudioFilesResponse
    {
        /// <summary>
        /// Initializes a new instance of the QueryAudioFilesResponse class.
        /// </summary>
        public QueryAudioFilesResponse()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the QueryAudioFilesResponse class.
        /// </summary>
        public QueryAudioFilesResponse(IList<QueryAudioFileResponse> audioFiles = default(IList<QueryAudioFileResponse>), int? totalCount = default(int?))
        {
            AudioFiles = audioFiles;
            TotalCount = totalCount;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "audioFiles")]
        public IList<QueryAudioFileResponse> AudioFiles { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "totalCount")]
        public int? TotalCount { get; set; }

    }
}
