// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Speech.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// SpeakPhoneMetadataResponseV3
    /// </summary>
    public partial class SpeakPhoneMetadataResponseV3
    {
        /// <summary>
        /// Initializes a new instance of the SpeakPhoneMetadataResponseV3
        /// class.
        /// </summary>
        public SpeakPhoneMetadataResponseV3()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the SpeakPhoneMetadataResponseV3
        /// class.
        /// </summary>
        public SpeakPhoneMetadataResponseV3(string ttsPhone = default(string), string sapiPhone = default(string), string ipaPhone = default(string))
        {
            TtsPhone = ttsPhone;
            SapiPhone = sapiPhone;
            IpaPhone = ipaPhone;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ttsPhone")]
        public string TtsPhone { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "sapiPhone")]
        public string SapiPhone { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ipaPhone")]
        public string IpaPhone { get; set; }

    }
}
