// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Speech.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// SpeakWordMetadataResponseV3
    /// </summary>
    public partial class SpeakWordMetadataResponseV3
    {
        /// <summary>
        /// Initializes a new instance of the SpeakWordMetadataResponseV3
        /// class.
        /// </summary>
        public SpeakWordMetadataResponseV3()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the SpeakWordMetadataResponseV3
        /// class.
        /// </summary>
        public SpeakWordMetadataResponseV3(string text = default(string), double? duration = default(double?), IList<double?> f0s = default(IList<double?>), IList<double?> f0MergedWithSilenceWord = default(IList<double?>), IList<SpeakSyllableMetadataResponseV3> syllables = default(IList<SpeakSyllableMetadataResponseV3>))
        {
            Text = text;
            Duration = duration;
            F0s = f0s;
            F0MergedWithSilenceWord = f0MergedWithSilenceWord;
            Syllables = syllables;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "text")]
        public string Text { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "duration")]
        public double? Duration { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "f0s")]
        public IList<double?> F0s { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "f0MergedWithSilenceWord")]
        public IList<double?> F0MergedWithSilenceWord { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "syllables")]
        public IList<SpeakSyllableMetadataResponseV3> Syllables { get; set; }

    }
}
