// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Speech.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// SpeakSyllableMetadataResponseV3
    /// </summary>
    public partial class SpeakSyllableMetadataResponseV3
    {
        /// <summary>
        /// Initializes a new instance of the SpeakSyllableMetadataResponseV3
        /// class.
        /// </summary>
        public SpeakSyllableMetadataResponseV3()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the SpeakSyllableMetadataResponseV3
        /// class.
        /// </summary>
        public SpeakSyllableMetadataResponseV3(string ttsPron = default(string), IList<SpeakPhoneMetadataResponseV3> phones = default(IList<SpeakPhoneMetadataResponseV3>))
        {
            TtsPron = ttsPron;
            Phones = phones;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ttsPron")]
        public string TtsPron { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "phones")]
        public IList<SpeakPhoneMetadataResponseV3> Phones { get; set; }

    }
}
