// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Speech.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// SpeakMetadataResponseV3
    /// </summary>
    public partial class SpeakMetadataResponseV3
    {
        /// <summary>
        /// Initializes a new instance of the SpeakMetadataResponseV3 class.
        /// </summary>
        public SpeakMetadataResponseV3()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the SpeakMetadataResponseV3 class.
        /// </summary>
        public SpeakMetadataResponseV3(IList<SpeakWordMetadataResponseV3> wordMetadatas = default(IList<SpeakWordMetadataResponseV3>), string ttsPron = default(string), string sapiPron = default(string), string ipaPron = default(string), string upsPron = default(string))
        {
            WordMetadatas = wordMetadatas;
            TtsPron = ttsPron;
            SapiPron = sapiPron;
            IpaPron = ipaPron;
            UpsPron = upsPron;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "wordMetadatas")]
        public IList<SpeakWordMetadataResponseV3> WordMetadatas { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ttsPron")]
        public string TtsPron { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "sapiPron")]
        public string SapiPron { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ipaPron")]
        public string IpaPron { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "upsPron")]
        public string UpsPron { get; set; }

    }
}
