// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Speech.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// SplitSsmlsResponseItemV3
    /// </summary>
    public partial class SplitSsmlsResponseItemV3
    {
        /// <summary>
        /// Initializes a new instance of the SplitSsmlsResponseItemV3 class.
        /// </summary>
        public SplitSsmlsResponseItemV3()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the SplitSsmlsResponseItemV3 class.
        /// </summary>
        public SplitSsmlsResponseItemV3(IList<SplitSsmlsResponseSegmentV3> segments, string errorMessage = default(string))
        {
            Segments = segments;
            ErrorMessage = errorMessage;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "segments")]
        public IList<SplitSsmlsResponseSegmentV3> Segments { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "errorMessage")]
        public string ErrorMessage { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (Segments == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Segments");
            }
            if (Segments != null)
            {
                foreach (var element in Segments)
                {
                    if (element != null)
                    {
                        element.Validate();
                    }
                }
            }
        }
    }
}
