// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Speech.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// SplitSsmlDefinitionV3
    /// </summary>
    public partial class SplitSsmlDefinitionV3
    {
        /// <summary>
        /// Initializes a new instance of the SplitSsmlDefinitionV3 class.
        /// </summary>
        public SplitSsmlDefinitionV3()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the SplitSsmlDefinitionV3 class.
        /// </summary>
        public SplitSsmlDefinitionV3(IList<string> ssmls, SplitSsmlOrPlainTextFileOptionsDefinitionV3 splitFileOptions = default(SplitSsmlOrPlainTextFileOptionsDefinitionV3))
        {
            Ssmls = ssmls;
            SplitFileOptions = splitFileOptions;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ssmls")]
        public IList<string> Ssmls { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "splitFileOptions")]
        public SplitSsmlOrPlainTextFileOptionsDefinitionV3 SplitFileOptions { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (Ssmls == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Ssmls");
            }
        }
    }
}
