// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Speech.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// SplitSsmlsResponseV3
    /// </summary>
    public partial class SplitSsmlsResponseV3
    {
        /// <summary>
        /// Initializes a new instance of the SplitSsmlsResponseV3 class.
        /// </summary>
        public SplitSsmlsResponseV3()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the SplitSsmlsResponseV3 class.
        /// </summary>
        public SplitSsmlsResponseV3(IList<SplitSsmlsResponseItemV3> ssmlSplitResults)
        {
            SsmlSplitResults = ssmlSplitResults;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ssmlSplitResults")]
        public IList<SplitSsmlsResponseItemV3> SsmlSplitResults { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (SsmlSplitResults == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "SsmlSplitResults");
            }
            if (SsmlSplitResults != null)
            {
                foreach (var element in SsmlSplitResults)
                {
                    if (element != null)
                    {
                        element.Validate();
                    }
                }
            }
        }
    }
}
