// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Speech.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// SplitSsmlsResponseSegmentV3
    /// </summary>
    public partial class SplitSsmlsResponseSegmentV3
    {
        /// <summary>
        /// Initializes a new instance of the SplitSsmlsResponseSegmentV3
        /// class.
        /// </summary>
        public SplitSsmlsResponseSegmentV3()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the SplitSsmlsResponseSegmentV3
        /// class.
        /// </summary>
        public SplitSsmlsResponseSegmentV3(string ssml, int charLenghtOfPlainText)
        {
            Ssml = ssml;
            CharLenghtOfPlainText = charLenghtOfPlainText;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ssml")]
        public string Ssml { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "charLenghtOfPlainText")]
        public int CharLenghtOfPlainText { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (Ssml == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Ssml");
            }
        }
    }
}
