// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Speech.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// SsmlSayAsTagCandidatesResponseV3
    /// </summary>
    public partial class SsmlSayAsTagCandidatesResponseV3
    {
        /// <summary>
        /// Initializes a new instance of the SsmlSayAsTagCandidatesResponseV3
        /// class.
        /// </summary>
        public SsmlSayAsTagCandidatesResponseV3()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the SsmlSayAsTagCandidatesResponseV3
        /// class.
        /// </summary>
        public SsmlSayAsTagCandidatesResponseV3(string displayName, string interpretName, IList<SsmlSayAsTagFormatMetadataResponseV3> formats)
        {
            DisplayName = displayName;
            InterpretName = interpretName;
            Formats = formats;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "displayName")]
        public string DisplayName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "interpretName")]
        public string InterpretName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "formats")]
        public IList<SsmlSayAsTagFormatMetadataResponseV3> Formats { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (DisplayName == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "DisplayName");
            }
            if (InterpretName == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "InterpretName");
            }
            if (Formats == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Formats");
            }
            if (Formats != null)
            {
                foreach (var element in Formats)
                {
                    if (element != null)
                    {
                        element.Validate();
                    }
                }
            }
        }
    }
}
