// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Speech.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// SsmlTagMatchMetadataResponseV3
    /// </summary>
    public partial class SsmlTagMatchMetadataResponseV3
    {
        /// <summary>
        /// Initializes a new instance of the SsmlTagMatchMetadataResponseV3
        /// class.
        /// </summary>
        public SsmlTagMatchMetadataResponseV3()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the SsmlTagMatchMetadataResponseV3
        /// class.
        /// </summary>
        /// <param name="updateTypes">Possible values include: 'None',
        /// 'Pronunciation', 'Break', 'Rate', 'Pitch', 'Range', 'Duration',
        /// 'Volume', 'Contour', 'Sub', 'Emphasis', 'Normalization', 'SayAs',
        /// 'Emotion', 'Clear', 'BoundaryTone', 'BackgroundMusic', 'Voice',
        /// 'ExpressAs', 'SoundEffect', 'Prompt', 'Text', 'Prosody',
        /// 'NotCrossVoice', 'All'</param>
        /// <param name="voiceTuningCategories">Possible values include:
        /// 'None', 'NormalVoice', 'NeuralVoice'</param>
        public SsmlTagMatchMetadataResponseV3(string updateTypes = default(string), string voiceTuningCategories = default(string), string voiceName = default(string))
        {
            UpdateTypes = updateTypes;
            VoiceTuningCategories = voiceTuningCategories;
            VoiceName = voiceName;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets possible values include: 'None', 'Pronunciation',
        /// 'Break', 'Rate', 'Pitch', 'Range', 'Duration', 'Volume', 'Contour',
        /// 'Sub', 'Emphasis', 'Normalization', 'SayAs', 'Emotion', 'Clear',
        /// 'BoundaryTone', 'BackgroundMusic', 'Voice', 'ExpressAs',
        /// 'SoundEffect', 'Prompt', 'Text', 'Prosody', 'NotCrossVoice', 'All'
        /// </summary>
        [JsonProperty(PropertyName = "updateTypes")]
        public string UpdateTypes { get; set; }

        /// <summary>
        /// Gets or sets possible values include: 'None', 'NormalVoice',
        /// 'NeuralVoice'
        /// </summary>
        [JsonProperty(PropertyName = "voiceTuningCategories")]
        public string VoiceTuningCategories { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "voiceName")]
        public string VoiceName { get; set; }

    }
}
