// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Speech.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// SsmlTagMetadataResponseV3
    /// </summary>
    public partial class SsmlTagMetadataResponseV3
    {
        /// <summary>
        /// Initializes a new instance of the SsmlTagMetadataResponseV3 class.
        /// </summary>
        public SsmlTagMetadataResponseV3()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the SsmlTagMetadataResponseV3 class.
        /// </summary>
        /// <param name="selectionMode">Possible values include: 'None',
        /// 'OnlyRangeSelection', 'OnlyPoint', 'RangeSelectionOrPoint'</param>
        public SsmlTagMetadataResponseV3(SsmlTagMatchMetadataResponseV3 matchMetadata = default(SsmlTagMatchMetadataResponseV3), bool? supportWordLevel = default(bool?), string selectionMode = default(string), bool? isDisabled = default(bool?), IList<SsmlTagParameterMetadataResponseV3> parameterMetadatas = default(IList<SsmlTagParameterMetadataResponseV3>))
        {
            MatchMetadata = matchMetadata;
            SupportWordLevel = supportWordLevel;
            SelectionMode = selectionMode;
            IsDisabled = isDisabled;
            ParameterMetadatas = parameterMetadatas;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "matchMetadata")]
        public SsmlTagMatchMetadataResponseV3 MatchMetadata { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "supportWordLevel")]
        public bool? SupportWordLevel { get; set; }

        /// <summary>
        /// Gets or sets possible values include: 'None', 'OnlyRangeSelection',
        /// 'OnlyPoint', 'RangeSelectionOrPoint'
        /// </summary>
        [JsonProperty(PropertyName = "selectionMode")]
        public string SelectionMode { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "isDisabled")]
        public bool? IsDisabled { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "parameterMetadatas")]
        public IList<SsmlTagParameterMetadataResponseV3> ParameterMetadatas { get; set; }

    }
}
