// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Speech.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// TestUpdate
    /// </summary>
    public partial class TestUpdate
    {
        /// <summary>
        /// Initializes a new instance of the TestUpdate class.
        /// </summary>
        public TestUpdate()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the TestUpdate class.
        /// </summary>
        /// <param name="project">The project, the dataset is associated
        /// with</param>
        /// <param name="displayName">The name of the object</param>
        /// <param name="description">The description of the object</param>
        public TestUpdate(EntityReference project = default(EntityReference), string displayName = default(string), string description = default(string))
        {
            Project = project;
            DisplayName = displayName;
            Description = description;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets the project, the dataset is associated with
        /// </summary>
        [JsonProperty(PropertyName = "project")]
        public EntityReference Project { get; set; }

        /// <summary>
        /// Gets or sets the name of the object
        /// </summary>
        [JsonProperty(PropertyName = "displayName")]
        public string DisplayName { get; set; }

        /// <summary>
        /// Gets or sets the description of the object
        /// </summary>
        [JsonProperty(PropertyName = "description")]
        public string Description { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (Project != null)
            {
                Project.Validate();
            }
        }
    }
}
