// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Speech.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// TuneSsmlMetadataResponseV3
    /// </summary>
    public partial class TuneSsmlMetadataResponseV3
    {
        /// <summary>
        /// Initializes a new instance of the TuneSsmlMetadataResponseV3 class.
        /// </summary>
        public TuneSsmlMetadataResponseV3()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the TuneSsmlMetadataResponseV3 class.
        /// </summary>
        /// <param
        /// name="supportedVoiceEmotionCategoryNames">IDictionary`2</param>
        /// <param name="supportedVoiceNusDomainNames">IDictionary`2</param>
        public TuneSsmlMetadataResponseV3(IList<SsmlTagMetadataResponseV3> tagMetadatas = default(IList<SsmlTagMetadataResponseV3>), IList<SsmlSayAsTagCandidatesResponseV3> sayAsTagInterpretMetadatas = default(IList<SsmlSayAsTagCandidatesResponseV3>), IList<string> supportedExportVoiceTypes = default(IList<string>), IDictionary<string, IList<string>> supportedVoiceEmotionCategoryNames = default(IDictionary<string, IList<string>>), IDictionary<string, IList<string>> supportedVoiceNusDomainNames = default(IDictionary<string, IList<string>>))
        {
            TagMetadatas = tagMetadatas;
            SayAsTagInterpretMetadatas = sayAsTagInterpretMetadatas;
            SupportedExportVoiceTypes = supportedExportVoiceTypes;
            SupportedVoiceEmotionCategoryNames = supportedVoiceEmotionCategoryNames;
            SupportedVoiceNusDomainNames = supportedVoiceNusDomainNames;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "tagMetadatas")]
        public IList<SsmlTagMetadataResponseV3> TagMetadatas { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "sayAsTagInterpretMetadatas")]
        public IList<SsmlSayAsTagCandidatesResponseV3> SayAsTagInterpretMetadatas { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "supportedExportVoiceTypes")]
        public IList<string> SupportedExportVoiceTypes { get; set; }

        /// <summary>
        /// Gets or sets iDictionary`2
        /// </summary>
        [JsonProperty(PropertyName = "supportedVoiceEmotionCategoryNames")]
        public IDictionary<string, IList<string>> SupportedVoiceEmotionCategoryNames { get; set; }

        /// <summary>
        /// Gets or sets iDictionary`2
        /// </summary>
        [JsonProperty(PropertyName = "supportedVoiceNusDomainNames")]
        public IDictionary<string, IList<string>> SupportedVoiceNusDomainNames { get; set; }

    }
}
