// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Speech.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// UploadVcgFileDefinitionV3
    /// </summary>
    public partial class UploadVcgFileDefinitionV3
    {
        /// <summary>
        /// Initializes a new instance of the UploadVcgFileDefinitionV3 class.
        /// </summary>
        public UploadVcgFileDefinitionV3()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the UploadVcgFileDefinitionV3 class.
        /// </summary>
        public UploadVcgFileDefinitionV3(string name, string content = default(string), IList<string> tags = default(IList<string>))
        {
            Name = name;
            Content = content;
            Tags = tags;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "content")]
        public string Content { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "tags")]
        public IList<string> Tags { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (Name == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Name");
            }
        }
    }
}
