// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Speech.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// UploadVcgFileResponseV3
    /// </summary>
    public partial class UploadVcgFileResponseV3
    {
        /// <summary>
        /// Initializes a new instance of the UploadVcgFileResponseV3 class.
        /// </summary>
        public UploadVcgFileResponseV3()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the UploadVcgFileResponseV3 class.
        /// </summary>
        public UploadVcgFileResponseV3(string errorMessage = default(string), VcgFile vcgFile = default(VcgFile), IList<VcgFile> vcgFiles = default(IList<VcgFile>))
        {
            ErrorMessage = errorMessage;
            VcgFile = vcgFile;
            VcgFiles = vcgFiles;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "errorMessage")]
        public string ErrorMessage { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "vcgFile")]
        public VcgFile VcgFile { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "vcgFiles")]
        public IList<VcgFile> VcgFiles { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (VcgFile != null)
            {
                VcgFile.Validate();
            }
            if (VcgFiles != null)
            {
                foreach (var element in VcgFiles)
                {
                    if (element != null)
                    {
                        element.Validate();
                    }
                }
            }
        }
    }
}
