// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Speech.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// VcgBlobEntityDefinition
    /// </summary>
    public partial class VcgBlobEntityDefinition
    {
        /// <summary>
        /// Initializes a new instance of the VcgBlobEntityDefinition class.
        /// </summary>
        public VcgBlobEntityDefinition()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the VcgBlobEntityDefinition class.
        /// </summary>
        /// <param name="artifactKind">Possible values include:
        /// 'DataImportReport', 'AudioFile', 'LanguageDataUserInput',
        /// 'LanguageDataImportResult', 'PronunciationDataUserInput',
        /// 'PronunciationDataImportResult', 'AcousticDataUserInputAudioFiles',
        /// 'AcousticDataUserInputIndexFile', 'AcousticDataImportReport',
        /// 'AcousticDataNormalizedAudioFiles',
        /// 'AcousticDataNormalizedIndexFile',
        /// 'AcousticDataNormalizedTranscription', 'TranscriptionResult',
        /// 'TranscriptionV21Result',
        /// 'TranscriptionV21NormalizedDisplayResult',
        /// 'TranscriptionOutputFile', 'TranscriptionResultsZip',
        /// 'AccuracyTestReferenceFile', 'AccuracyTestResult',
        /// 'ScoringSummaryFile', 'ScoringDetailsFile', 'ScoringMapping',
        /// 'DeploymentDataExportResult', 'SpeechModelFile', 'ReportFile',
        /// 'LogAudio', 'LogTranscription'</param>
        public VcgBlobEntityDefinition(System.Guid id, string artifactKind, string fileName = default(string), string endpointWithSas = default(string))
        {
            Id = id;
            ArtifactKind = artifactKind;
            FileName = fileName;
            EndpointWithSas = endpointWithSas;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public System.Guid Id { get; set; }

        /// <summary>
        /// Gets or sets possible values include: 'DataImportReport',
        /// 'AudioFile', 'LanguageDataUserInput', 'LanguageDataImportResult',
        /// 'PronunciationDataUserInput', 'PronunciationDataImportResult',
        /// 'AcousticDataUserInputAudioFiles',
        /// 'AcousticDataUserInputIndexFile', 'AcousticDataImportReport',
        /// 'AcousticDataNormalizedAudioFiles',
        /// 'AcousticDataNormalizedIndexFile',
        /// 'AcousticDataNormalizedTranscription', 'TranscriptionResult',
        /// 'TranscriptionV21Result',
        /// 'TranscriptionV21NormalizedDisplayResult',
        /// 'TranscriptionOutputFile', 'TranscriptionResultsZip',
        /// 'AccuracyTestReferenceFile', 'AccuracyTestResult',
        /// 'ScoringSummaryFile', 'ScoringDetailsFile', 'ScoringMapping',
        /// 'DeploymentDataExportResult', 'SpeechModelFile', 'ReportFile',
        /// 'LogAudio', 'LogTranscription'
        /// </summary>
        [JsonProperty(PropertyName = "artifactKind")]
        public string ArtifactKind { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "fileName")]
        public string FileName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "endpointWithSas")]
        public string EndpointWithSas { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (ArtifactKind == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "ArtifactKind");
            }
        }
    }
}
