// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Speech.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// VoiceTestDefinitionV3
    /// </summary>
    public partial class VoiceTestDefinitionV3
    {
        /// <summary>
        /// Initializes a new instance of the VoiceTestDefinitionV3 class.
        /// </summary>
        public VoiceTestDefinitionV3()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the VoiceTestDefinitionV3 class.
        /// </summary>
        /// <param name="text">Information about the text used in the voice
        /// test</param>
        /// <param name="model">Information about the models used in the voice
        /// test</param>
        /// <param name="voiceTestKind">The kind of this test (e.g. Text,
        /// SSML). Possible values include: 'None', 'Text', 'SSML'</param>
        public VoiceTestDefinitionV3(string text, ModelIdentity model, string voiceTestKind, ProjectIdentity project = default(ProjectIdentity))
        {
            Project = project;
            Text = text;
            Model = model;
            VoiceTestKind = voiceTestKind;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "project")]
        public ProjectIdentity Project { get; set; }

        /// <summary>
        /// Gets or sets information about the text used in the voice test
        /// </summary>
        [JsonProperty(PropertyName = "text")]
        public string Text { get; set; }

        /// <summary>
        /// Gets or sets information about the models used in the voice test
        /// </summary>
        [JsonProperty(PropertyName = "model")]
        public ModelIdentity Model { get; set; }

        /// <summary>
        /// Gets or sets the kind of this test (e.g. Text, SSML). Possible
        /// values include: 'None', 'Text', 'SSML'
        /// </summary>
        [JsonProperty(PropertyName = "voiceTestKind")]
        public string VoiceTestKind { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (Text == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Text");
            }
            if (Model == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Model");
            }
            if (VoiceTestKind == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "VoiceTestKind");
            }
            if (Project != null)
            {
                Project.Validate();
            }
            if (Text != null)
            {
                if (Text.Length > 1024)
                {
                    throw new ValidationException(ValidationRules.MaxLength, "Text", 1024);
                }
                if (Text.Length < 0)
                {
                    throw new ValidationException(ValidationRules.MinLength, "Text", 0);
                }
            }
            if (Model != null)
            {
                Model.Validate();
            }
        }
    }
}
