// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Speech.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// VoiceEndpoint
    /// </summary>
    public partial class VoiceEndpoint
    {
        /// <summary>
        /// Initializes a new instance of the VoiceEndpoint class.
        /// </summary>
        public VoiceEndpoint()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the VoiceEndpoint class.
        /// </summary>
        /// <param name="id">The identifier of this entity</param>
        /// <param name="name">The name of the object</param>
        /// <param name="endpointKind">The kind of this endpoint (e.g. custom
        /// speech, custom voice ...). Possible values include:
        /// 'SpeechRecognition', 'CustomVoice', 'LanguageIdentification',
        /// 'PronunciationScore'</param>
        /// <param name="locale">The locale of the contained data</param>
        /// <param name="description">The description of the object</param>
        /// <param name="endpointUrls">The list of endpoint urls</param>
        /// <param name="lastActionDateTime">The time-stamp when the current
        /// status was entered</param>
        /// <param name="status">The status of the object. Possible values
        /// include: 'NotStarted', 'Running', 'Succeeded', 'Failed'</param>
        /// <param name="createdDateTime">The time-stamp when the object was
        /// created</param>
        /// <param name="contentLoggingEnabled">A value indicating whether
        /// content logging (audio &amp;amp; transcriptions) is being used for
        /// a deployment</param>
        /// <param name="text">The text used to adapt a language model for this
        /// endpoint</param>
        /// <param name="modelsProperty">Information about the deployed
        /// models</param>
        /// <param name="properties">The custom properties of this
        /// entity</param>
        /// <param name="project">The project, the entity is associated
        /// with</param>
        public VoiceEndpoint(System.Guid id, string name, string endpointKind, string locale, string description = default(string), IDictionary<string, string> endpointUrls = default(IDictionary<string, string>), System.DateTime? lastActionDateTime = default(System.DateTime?), string status = default(string), System.DateTime? createdDateTime = default(System.DateTime?), bool? contentLoggingEnabled = default(bool?), string text = default(string), IList<VoiceModel> modelsProperty = default(IList<VoiceModel>), IDictionary<string, string> properties = default(IDictionary<string, string>), ProjectIdentity project = default(ProjectIdentity))
        {
            Id = id;
            Name = name;
            Description = description;
            EndpointUrls = endpointUrls;
            EndpointKind = endpointKind;
            LastActionDateTime = lastActionDateTime;
            Status = status;
            CreatedDateTime = createdDateTime;
            ContentLoggingEnabled = contentLoggingEnabled;
            Text = text;
            ModelsProperty = modelsProperty;
            Properties = properties;
            Locale = locale;
            Project = project;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets the identifier of this entity
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public System.Guid Id { get; set; }

        /// <summary>
        /// Gets or sets the name of the object
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// Gets or sets the description of the object
        /// </summary>
        [JsonProperty(PropertyName = "description")]
        public string Description { get; set; }

        /// <summary>
        /// Gets the list of endpoint urls
        /// </summary>
        [JsonProperty(PropertyName = "endpointUrls")]
        public IDictionary<string, string> EndpointUrls { get; private set; }

        /// <summary>
        /// Gets or sets the kind of this endpoint (e.g. custom speech, custom
        /// voice ...). Possible values include: 'SpeechRecognition',
        /// 'CustomVoice', 'LanguageIdentification', 'PronunciationScore'
        /// </summary>
        [JsonProperty(PropertyName = "endpointKind")]
        public string EndpointKind { get; set; }

        /// <summary>
        /// Gets the time-stamp when the current status was entered
        /// </summary>
        [JsonProperty(PropertyName = "lastActionDateTime")]
        public System.DateTime? LastActionDateTime { get; private set; }

        /// <summary>
        /// Gets the status of the object. Possible values include:
        /// 'NotStarted', 'Running', 'Succeeded', 'Failed'
        /// </summary>
        [JsonProperty(PropertyName = "status")]
        public string Status { get; private set; }

        /// <summary>
        /// Gets the time-stamp when the object was created
        /// </summary>
        [JsonProperty(PropertyName = "createdDateTime")]
        public System.DateTime? CreatedDateTime { get; private set; }

        /// <summary>
        /// Gets or sets a value indicating whether content logging (audio
        /// &amp;amp;amp; transcriptions) is being used for a deployment
        /// </summary>
        [JsonProperty(PropertyName = "contentLoggingEnabled")]
        public bool? ContentLoggingEnabled { get; set; }

        /// <summary>
        /// Gets or sets the text used to adapt a language model for this
        /// endpoint
        /// </summary>
        [JsonProperty(PropertyName = "text")]
        public string Text { get; set; }

        /// <summary>
        /// Gets or sets information about the deployed models
        /// </summary>
        [JsonProperty(PropertyName = "models")]
        public IList<VoiceModel> ModelsProperty { get; set; }

        /// <summary>
        /// Gets or sets the custom properties of this entity
        /// </summary>
        [JsonProperty(PropertyName = "properties")]
        public IDictionary<string, string> Properties { get; set; }

        /// <summary>
        /// Gets or sets the locale of the contained data
        /// </summary>
        [JsonProperty(PropertyName = "locale")]
        public string Locale { get; set; }

        /// <summary>
        /// Gets or sets the project, the entity is associated with
        /// </summary>
        [JsonProperty(PropertyName = "project")]
        public ProjectIdentity Project { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (Name == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Name");
            }
            if (EndpointKind == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "EndpointKind");
            }
            if (Locale == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Locale");
            }
            if (ModelsProperty != null)
            {
                foreach (var element in ModelsProperty)
                {
                    if (element != null)
                    {
                        element.Validate();
                    }
                }
            }
            if (Project != null)
            {
                Project.Validate();
            }
        }
    }
}
