// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Speech.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// VoiceTestUpdate
    /// </summary>
    public partial class VoiceTestUpdate
    {
        /// <summary>
        /// Initializes a new instance of the VoiceTestUpdate class.
        /// </summary>
        public VoiceTestUpdate()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the VoiceTestUpdate class.
        /// </summary>
        /// <param name="project">The project, the entity is associated
        /// with</param>
        public VoiceTestUpdate(ProjectIdentity project = default(ProjectIdentity))
        {
            Project = project;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets the project, the entity is associated with
        /// </summary>
        [JsonProperty(PropertyName = "project")]
        public ProjectIdentity Project { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (Project != null)
            {
                Project.Validate();
            }
        }
    }
}
