// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Speech.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// VoiceSynthesisDefinition
    /// </summary>
    public partial class VoiceSynthesisDefinition
    {
        /// <summary>
        /// Initializes a new instance of the VoiceSynthesisDefinition class.
        /// </summary>
        public VoiceSynthesisDefinition()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the VoiceSynthesisDefinition class.
        /// </summary>
        /// <param name="modelsProperty">The list of models used for the voice
        /// synthesis.
        /// The model could be a basic tts model or a customized tts
        /// model</param>
        /// <param name="outputFormat">The audio output format</param>
        /// <param name="locale">The locale of the contained data</param>
        /// <param name="name">The name of the object</param>
        /// <param name="description">The description of the object</param>
        /// <param name="properties">The custom properties of this
        /// entity</param>
        public VoiceSynthesisDefinition(IList<ModelIdentity> modelsProperty, string outputFormat, string locale, string name, string description = default(string), IDictionary<string, string> properties = default(IDictionary<string, string>))
        {
            ModelsProperty = modelsProperty;
            OutputFormat = outputFormat;
            Locale = locale;
            Name = name;
            Description = description;
            Properties = properties;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets the list of models used for the voice synthesis.
        /// The model could be a basic tts model or a customized tts model
        /// </summary>
        [JsonProperty(PropertyName = "models")]
        public IList<ModelIdentity> ModelsProperty { get; set; }

        /// <summary>
        /// Gets or sets the audio output format
        /// </summary>
        [JsonProperty(PropertyName = "outputFormat")]
        public string OutputFormat { get; set; }

        /// <summary>
        /// Gets or sets the locale of the contained data
        /// </summary>
        [JsonProperty(PropertyName = "locale")]
        public string Locale { get; set; }

        /// <summary>
        /// Gets or sets the name of the object
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// Gets or sets the description of the object
        /// </summary>
        [JsonProperty(PropertyName = "description")]
        public string Description { get; set; }

        /// <summary>
        /// Gets or sets the custom properties of this entity
        /// </summary>
        [JsonProperty(PropertyName = "properties")]
        public IDictionary<string, string> Properties { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (ModelsProperty == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "ModelsProperty");
            }
            if (OutputFormat == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "OutputFormat");
            }
            if (Locale == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Locale");
            }
            if (Name == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Name");
            }
            if (ModelsProperty != null)
            {
                foreach (var element in ModelsProperty)
                {
                    if (element != null)
                    {
                        element.Validate();
                    }
                }
            }
        }
    }
}
