// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Speech.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// WebHookUpdate
    /// </summary>
    public partial class WebHookUpdate
    {
        /// <summary>
        /// Initializes a new instance of the WebHookUpdate class.
        /// </summary>
        public WebHookUpdate()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the WebHookUpdate class.
        /// </summary>
        /// <param name="configuration">The configuration of the web hook
        /// registration.
        ///
        /// If the property secret is omitted or contains an empty string in
        /// the PATCH request,
        /// no signature hash will be calculated.
        ///
        /// When retrieving web hook registration information from the service,
        /// the secret is always omitted</param>
        /// <param name="active">A value indicating whether callbacks to the
        /// registered URL are made or not</param>
        /// <param name="events">A value indicating the webhook event
        /// kinds</param>
        /// <param name="displayName">The name of the object</param>
        /// <param name="description">The description of the object</param>
        public WebHookUpdate(WebHookConfigurationUpdate configuration = default(WebHookConfigurationUpdate), bool? active = default(bool?), IList<string> events = default(IList<string>), string displayName = default(string), string description = default(string))
        {
            Configuration = configuration;
            Active = active;
            Events = events;
            DisplayName = displayName;
            Description = description;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets the configuration of the web hook registration.
        ///
        /// If the property secret is omitted or contains an empty string in
        /// the PATCH request,
        /// no signature hash will be calculated.
        ///
        /// When retrieving web hook registration information from the service,
        /// the secret is always omitted
        /// </summary>
        [JsonProperty(PropertyName = "configuration")]
        public WebHookConfigurationUpdate Configuration { get; set; }

        /// <summary>
        /// Gets or sets a value indicating whether callbacks to the registered
        /// URL are made or not
        /// </summary>
        [JsonProperty(PropertyName = "active")]
        public bool? Active { get; set; }

        /// <summary>
        /// Gets or sets a value indicating the webhook event kinds
        /// </summary>
        [JsonProperty(PropertyName = "events")]
        public IList<string> Events { get; set; }

        /// <summary>
        /// Gets or sets the name of the object
        /// </summary>
        [JsonProperty(PropertyName = "displayName")]
        public string DisplayName { get; set; }

        /// <summary>
        /// Gets or sets the description of the object
        /// </summary>
        [JsonProperty(PropertyName = "description")]
        public string Description { get; set; }

    }
}
