// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Speech.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// WebHookConfiguration
    /// </summary>
    public partial class WebHookConfiguration
    {
        /// <summary>
        /// Initializes a new instance of the WebHookConfiguration class.
        /// </summary>
        public WebHookConfiguration()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the WebHookConfiguration class.
        /// </summary>
        /// <param name="url">The registered URL that will be used to send the
        /// POST requests for the registered events to</param>
        /// <param name="secret">A secret that will be used to create a SHA256
        /// hash of the payload with the secret as HMAC key.
        /// This hash will be set as X-MicrosoftSpeechServices-Signature header
        /// when calling back into the registered URL</param>
        public WebHookConfiguration(string url, string secret = default(string))
        {
            Url = url;
            Secret = secret;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets the registered URL that will be used to send the POST
        /// requests for the registered events to
        /// </summary>
        [JsonProperty(PropertyName = "url")]
        public string Url { get; set; }

        /// <summary>
        /// Gets or sets a secret that will be used to create a SHA256 hash of
        /// the payload with the secret as HMAC key.
        /// This hash will be set as X-MicrosoftSpeechServices-Signature header
        /// when calling back into the registered URL
        /// </summary>
        [JsonProperty(PropertyName = "secret")]
        public string Secret { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (Url == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Url");
            }
        }
    }
}
