// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Speech.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// WebHookLinks
    /// </summary>
    public partial class WebHookLinks
    {
        /// <summary>
        /// Initializes a new instance of the WebHookLinks class.
        /// </summary>
        public WebHookLinks()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the WebHookLinks class.
        /// </summary>
        /// <param name="ping">The URL that can be used to trigger the sending
        /// of a ping event to the registered URL of a web hook
        /// registration</param>
        /// <param name="test">The URL that can be used sending test events to
        /// the registered URL of a web hook registration</param>
        public WebHookLinks(string ping = default(string), string test = default(string))
        {
            Ping = ping;
            Test = test;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets the URL that can be used to trigger the sending of a ping
        /// event to the registered URL of a web hook registration
        /// </summary>
        [JsonProperty(PropertyName = "ping")]
        public string Ping { get; private set; }

        /// <summary>
        /// Gets the URL that can be used sending test events to the registered
        /// URL of a web hook registration
        /// </summary>
        [JsonProperty(PropertyName = "test")]
        public string Test { get; private set; }

    }
}
